# Use the official .NET SDK to compile the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS Compiler

WORKDIR /source

# Copy csproj and restore as distinct layers
COPY ./*.csproj .
RUN dotnet restore

# copy and publish app and libraries
COPY . .
ENTRYPOINT dotnet publish \
    -c ${CONFIGURATION} \
    --no-restore \
    -p:AssemblyName=${EXECUTABLE_NAME}