version: '3'
services:
  postgres-database:
    image: postgres:16.3
    container_name: postgres-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - main-network
volumes:
  postgres-data:
networks:
  main-network:
    driver: bridge