# Use the official .NET SDK to compile the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS Compiler

# Set the working directory
WORKDIR /app

# Environment variables for compilation configuration
ENV CONFIGURATION=Release
ENV EXECUTABLE_NAME=SelfContainedDeployment

ENTRYPOINT ["sh", "-c", "dotnet publish -c $CONFIGURATION --self-contained --runtime linux-x64 --verbosity=normal -p:AssemblyName=$EXECUTABLE_NAME"]