using System.ComponentModel.DataAnnotations;

public class Company {
    // Guid types will be autogenerated by default.
    // For EF Core to consider the column as the primary key of the
    // model, you need to name it as "Id" or "{ModelName}Id".
    public Guid CompanyId { get; set; }
    // Data annotations limit the size of the column in the database.
    [MaxLength(50)]
    public string Name { get; set; }
    // This model is the parent of a OneToMany relationship with the Trainee
    // model.
    // Defaults to a null forgiving operator to avoid warnings about 
    // uninitialized properties.
    public ICollection<Trainee> Trainees { get; } = new List<Trainee>();
    // This model participates in an optional OneToOne relationship with the 
    // Address model
    public Address? Address { get; set; }

    // The constructor supports Nullable Reference Types (NRT), which 
    // removes the warnings about uninitialized properties.
    public Company(string name) {
        Name = name;
    }
}